# version: '3.8'

services:
  job-db:
    image: postgres:15
    container_name: job-db
    environment:
      POSTGRES_DB: jobdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Saran@2002
    ports:
      - "5435:5432"
    volumes:
      - job-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  company-db:
    image: postgres:15
    container_name: company-db
    environment:
      POSTGRES_DB: companydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Saran@2002
    ports:
      - "5433:5432"
    volumes:
      - company-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  review-db:
    image: postgres:15
    container_name: review-db
    environment:
      POSTGRES_DB: reviewdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Saran@2002
    ports:
      - "5434:5432"
    volumes:
      - review-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  zipkin:
    build:
      context: .
      dockerfile: zipkin/Dockerfile
    container_name: zipkin
    ports:
      - "9411:9411"

  servicems:
    build:
      context: ./servicems
    container_name: servicems
    ports:
      - "8761:8761"
    environment:
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servicems:8761/eureka/
    depends_on:
      zipkin:
        condition: service_started

  companyms:
    build:
      context: ./companyms
    container_name: companyms
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://company-db:5432/companydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Saran@2002
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servicems:8761/eureka/
    depends_on:
      company-db:
        condition: service_healthy
      zipkin:
        condition: service_started
      servicems:
        condition: service_started

  jobms:
    build:
      context: ./jobms
    container_name: jobms
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://job-db:5432/jobdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Saran@2002
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servicems:8761/eureka/
    depends_on:
      job-db:
        condition: service_healthy
      zipkin:
        condition: service_started
      servicems:
        condition: service_started

  reviewms:
    build:
      context: ./reviewms
    container_name: reviewms
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://review-db:5432/reviewdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Saran@2002
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servicems:8761/eureka/
    depends_on:
      review-db:
        condition: service_healthy
      zipkin:
        condition: service_started
      servicems:
        condition: service_started

volumes:
  job-data:
  company-data:
  review-data:




# services:
#   zipkin:
#     build:
#       context: .
#       dockerfile: zipkin/Dockerfile
#     container_name: zipkin
#     ports:
#       - "9411:9411"

#   servicems:
#     build:
#       context: ./servicems
#     container_name: servicems
#     ports:
#       - "8761:8761"
#     environment:
#       SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
#       EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servicems:8761/eureka/
#     depends_on:
#       zipkin:
#         condition: service_started

#   companyms:
#     build:
#       context: ./companyms
#     container_name: companyms
#     ports:
#       - "8081:8081"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/companydb
#       SPRING_DATASOURCE_USERNAME: postgres
#       SPRING_DATASOURCE_PASSWORD: Saran@2002
#       SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
#       EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servicems:8761/eureka/
#     depends_on:
#       zipkin:
#         condition: service_started
#       servicems:
#         condition: service_started

#   jobms:
#     build:
#       context: ./jobms
#     container_name: jobms
#     ports:
#       - "8082:8082"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/jobdb
#       SPRING_DATASOURCE_USERNAME: postgres
#       SPRING_DATASOURCE_PASSWORD: Saran@2002
#       SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
#       EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servicems:8761/eureka/
#     depends_on:
#       zipkin:
#         condition: service_started
#       servicems:
#         condition: service_started

#   reviewms:
#     build:
#       context: ./reviewms
#     container_name: reviewms
#     ports:
#       - "8084:8084"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/reviewdb
#       SPRING_DATASOURCE_USERNAME: postgres
#       SPRING_DATASOURCE_PASSWORD: Saran@2002
#       SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
#       EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servicems:8761/eureka/
#     depends_on:
#       zipkin:
#         condition: service_started
#       servicems:
#         condition: service_started

# volumes:
#   job-data:
#   company-data:
#   review-data: